version: "3.9"  # latest stable Docker Compose syntax

services:
  node-app:
    build: .
    image: weshare:latest
    container_name: node-app-container: latest
    ports:
      - "3000:3000"  # map container port 3000 to host port 3000
    restart: unless-stopped
    environment:
      NODE_ENV: production
