name: cd/main
on:
  push:
    branches: ['master','dev','stage']
permissions:
    contents: read
    actions: write
jobs: 
  deploy-to-prod:
    runs-on: self-hosted
    environment: prod

    if: github.ref=='refs/heads/master'
    steps:
      - name: checkout the code
        uses: actions/checkout@v4
      - name: build docker image
        run: |
          cd $GITHUB_WORKSPACE
          sudo docker-compose build
          if [ "$(sudo docker ps -aqf name=node-app-container)" ];then
            sudo docker rm -f node-app-container
          fi
          sudo docker-compose up -d --force-recreate
          sudo docker image prune -f
      
      - name: Notify dedicated teams channel
        uses: jdcargile/ms-teams-notification@v1.4
        with:
          github-token: ${{ github.token }} # this will use the runner's token.
          ms-teams-webhook-uri: ${{ secrets.TEAMS_INCOMING_WEBHOOK_URL }}
          notification-summary: deployment done. 
          notification-color: 17a2b8
          timezone: America/Denver
          verbose-logging: true

          
