name: cd/main
on:
  push:
    branches: ['master','dev','stage']
permissions:
    contents: read
    actions: write
jobs: 
  deploy-to-prod:
    runs-on: self-hosted
    environment: prod

    if: github.ref=='refs/heads/master'
    steps:
      - name: checkout the code
        uses: actions/checkout@v4
      - name: build docker image
        run: |
          cd $GITHUB_WORKSPACE
          sudo docker-compose build
          if [ "$(sudo docker ps -aqf name=node-app-container)" ];then
            sudo docker rm -f node-app-container
          fi
          sudo docker-compose up -d --force-recreate
          sudo docker image prune -f
      
      - name: Notify Microsoft Teams
        if: always() # ensures it runs even if previous steps fail
        uses: dawidd6/action-send-webhook@v3
        with:
         webhook_url: ${{ secrets.TEAMS_WEBHOOK_URL }}
         content: |
          {
            "title": "GitHub Actions Notification",
            "text": "Workflow **${{ github.workflow }}** ran on branch **${{ github.ref_name }}**.\nStatus: **${{ job.status }}**"
          }    
          

          
