name: cd/main
on:
  push:
    branches: ['master','dev','stage']
permissions:
    contents: read
    actions: write

    
jobs: 
  deploy-to-prod:
    runs-on: self-hosted
    environment: prod

    if: github.ref=='refs/heads/master'
    steps:
      - name: checkout the code
        uses: actions/checkout@v4
      - name: build docker image
        run: |
          cd $GITHUB_WORKSPACE
          if [ "$(docker ps -aqf name=node-app-container)" ];then
            sudo docker rm -f node-app-container
            sudo docker rmi -f weshare:latest
          fi 
          sudo docker-compose up -d 
          sudo docker images

          
